# Generated by Django 3.2 on 2021-04-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=45)),
            ],
        ),
    ]
