# Generated by Django 3.2 on 2021-04-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0003_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
