# Generated by Django 3.2 on 2021-04-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('autor', models.CharField(max_length=45)),
                ('editora', models.CharField(max_length=45)),
                ('ano', models.IntegerField()),
                ('preco', models.IntegerField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Funcionario.funcionario')),
            ],
        ),
    ]
